### ISSUE TITLE
GEXF Layout revisions

### ISSUE THREAD

**Issue by mginda** [cns-iu/agc1#1]
- [x] Revise layout and color selection for ACG1 co-author network 
- [x] Upload GEXF file to GH
- [x] Share results with Bruce and team

**Comment by mginda** [comment]
Issue with some nodes in GEXF not being visualized in final network website.

**Comment by bherr2** [comment]
This should be fixed in the latest version, see:
https://cns-iu.github.io/agc1/

**Comment by katyb** [comment]
Size is #Citations
Line thickness is #Joint Publications
?


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics, Computing, and Engineering, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by bherr2** [comment]
Not yet, I couldn't remember what you said for that. I'll add it though.
